### ISSUE TITLE
With tryLock it is not always safe to continue

### ISSUE THREAD

**Issue by karussell** [mojgh/JKeyLockManager#5]
I stumbled over your library when reading about [this](http://stackoverflow.com/q/38910943/194609), [this](http://stackoverflow.com/q/5639870/194609) and [this](http://stackoverflow.com/q/39675003/194609) questions at stackoverflow. And I think the use is not safe. Why are you always continuing after the `tryLock`? 

https://github.com/mojgh/JKeyLockManager/blob/master/src/main/java/de/jkeylockmanager/manager/implementation/lockstripe/StripedKeyLockManager.java#L115

IMO you should either use `lock` or `tryLock` in a loop until it returns true. See tryLock javadocs:

_Returns: true if the lock was free and was acquired by the current thread, or the lock was already held by the current thread; and *_false*\* otherwise*

**Comment by bokken** [comment]
The key distinction is that tryLock is being called on CountingLock, which is where the "real" work of interacting with a Lock from the jre takes place. Here, if tryLock returns false, an exception is thrown.

https://github.com/mojgh/JKeyLockManager/blob/master/src/main/java/de/jkeylockmanager/manager/implementation/lockstripe/CountingLock.java#L108

**Comment by karussell** [comment]
Ah, sorry thought you are using the standard lock. You could rename the method to improve readability :)
